; PlatformIO Project Configuration File
;
; Metro ESP32-S3 firmware for the SASE AQI drone.

[env:adafruit_metro_esp32s3]
platform = espressif32
board = adafruit_metro_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
	adafruit/Adafruit BNO08x@^1.2.5
	adafruit/Adafruit BusIO@^1.17.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	https://github.com/adafruit/Adafruit_VL53L0X.git
	sparkfun/SparkFun LPS28DFW Arduino Library@^1.0.0
